version: "3.8"
services:
  backend_one:
    build: ./one
    ports:
    - 127.0.0.1:1111:1111
    container_name: backend_one
    depends_on:
    - database_one
    environment:
      POSTGRES_HOST_ONE: ${POSTGRES_HOST_ONE}
      POSTGRES_DB_ONE: ${POSTGRES_DB_ONE}
      POSTGRES_USER_ONE: ${POSTGRES_USER_ONE}
      POSTGRES_PASSWORD_ONE: ${POSTGRES_PASSWORD_ONE}
      DB_DIALECT_ONE: ${DB_DIALECT_ONE}
      APP_PORT_ONE: ${APP_PORT_ONE}
      APP_PORT_TWO: ${APP_PORT_TWO}
      DB_PORT_ONE: ${DB_PORT_ONE}
      BACKEND_CONTAINER_NAME_TWO: ${BACKEND_CONTAINER_NAME_TWO}
  database_one:
    image: postgres:16.1-bookworm
    container_name: database_one
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_ONE}
      POSTGRES_USER: ${POSTGRES_USER_ONE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ONE}
    ports:  
    - 2222:5432
    # volumes:
    # - db:/var/lib/postgresql/data
  backend_two:
    build: ./two
    ports:
    - 127.0.0.1:3333:3333
    container_name: backend_two
    depends_on:
    - database_two
    environment:
      POSTGRES_HOST_TWO: ${POSTGRES_HOST_TWO}
      POSTGRES_DB_TWO: ${POSTGRES_DB_TWO}
      POSTGRES_USER_TWO: ${POSTGRES_USER_TWO}
      POSTGRES_PASSWORD_TWO: ${POSTGRES_PASSWORD_TWO}
      DB_DIALECT_TWO: ${DB_DIALECT_TWO}
      APP_PORT_TWO: ${APP_PORT_TWO}
      DB_PORT_TWO: ${DB_PORT_TWO}
  database_two:
    image: postgres:16.1-bookworm
    container_name: database_two
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TWO}
      POSTGRES_USER: ${POSTGRES_USER_TWO}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TWO}
    ports:  
    - 4444:5432
    # volumes:
    # - db:/var/lib/postgresql/data
# volumes:
  # db: